-- BELLAS IMPORTS — Supabase database
-- Execute este arquivo no SQL Editor do Supabase.

create extension if not exists pgcrypto;

create table if not exists public.clientes (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  whatsapp text,
  cidade text,
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.produtos (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  sku text unique not null,
  categoria text,
  custo numeric(12,2) not null default 0,
  preco_venda numeric(12,2) not null default 0,
  estoque integer not null default 0,
  estoque_minimo integer not null default 3,
  canais text[] not null default array['WhatsApp'],
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.viagens (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  data_viagem date,
  status text not null default 'Planejada',
  orcamento numeric(12,2) not null default 0,
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.itens_viagem (
  id uuid primary key default gen_random_uuid(),
  viagem_id uuid references public.viagens(id) on delete cascade,
  produto_id uuid references public.produtos(id) on delete set null,
  produto_nome text not null,
  quantidade integer not null default 1,
  custo_alvo numeric(12,2) not null default 0,
  status text not null default 'A comprar',
  created_at timestamptz not null default now()
);

create table if not exists public.pedidos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  cliente_id uuid references public.clientes(id) on delete set null,
  cliente_nome text,
  whatsapp text,
  viagem_id uuid references public.viagens(id) on delete set null,
  total numeric(12,2) not null default 0,
  status text not null default 'Aguardando compra',
  origem text not null default 'WhatsApp',
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pedido_itens (
  id uuid primary key default gen_random_uuid(),
  pedido_id uuid not null references public.pedidos(id) on delete cascade,
  produto_id uuid references public.produtos(id) on delete set null,
  produto_nome text not null,
  quantidade integer not null default 1,
  preco_unitario numeric(12,2) not null default 0,
  subtotal numeric(12,2) generated always as (quantidade * preco_unitario) stored
);

create table if not exists public.movimentacoes_estoque (
  id uuid primary key default gen_random_uuid(),
  produto_id uuid not null references public.produtos(id) on delete cascade,
  tipo text not null check (tipo in ('Entrada','Saída','Reserva','Cancelamento de reserva')),
  quantidade integer not null check (quantidade > 0),
  motivo text,
  referencia_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.lancamentos_caixa (
  id uuid primary key default gen_random_uuid(),
  tipo text not null check (tipo in ('Entrada','Saída')),
  descricao text not null,
  categoria text,
  conta text,
  valor numeric(12,2) not null default 0,
  status text not null default 'Pago',
  data date not null default current_date,
  referencia_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.integracoes (
  id uuid primary key default gen_random_uuid(),
  canal text unique not null,
  ativo boolean not null default false,
  configuracao jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- Índices
create index if not exists idx_clientes_whatsapp on public.clientes(whatsapp);
create index if not exists idx_produtos_categoria on public.produtos(categoria);
create index if not exists idx_pedidos_status on public.pedidos(status);
create index if not exists idx_pedidos_created on public.pedidos(created_at desc);
create index if not exists idx_mov_estoque_produto on public.movimentacoes_estoque(produto_id);
create index if not exists idx_caixa_data on public.lancamentos_caixa(data desc);

-- RLS
alter table public.clientes enable row level security;
alter table public.produtos enable row level security;
alter table public.viagens enable row level security;
alter table public.itens_viagem enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedido_itens enable row level security;
alter table public.movimentacoes_estoque enable row level security;
alter table public.lancamentos_caixa enable row level security;
alter table public.integracoes enable row level security;

-- Para o primeiro protótipo privado, usuários autenticados podem fazer tudo.
-- Antes de produção, crie perfis/roles e restrinja por usuário/empresa.
do $$
declare t text;
begin
  foreach t in array array[
    'clientes','produtos','viagens','itens_viagem','pedidos',
    'pedido_itens','movimentacoes_estoque','lancamentos_caixa','integracoes'
  ] loop
    execute format('drop policy if exists "auth_all_%s" on public.%I', t, t);
    execute format('create policy "auth_all_%s" on public.%I for all to authenticated using (true) with check (true)', t, t);
  end loop;
end $$;

-- Seed inicial
insert into public.integracoes (canal) values
  ('WhatsApp Business'),
  ('Mercado Livre'),
  ('Instagram')
on conflict (canal) do nothing;
